default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: webmail_development

test:
  <<: *default
  database: webmail_test

production:
  <<: *default
  database: webmail_production
